<?php

namespace App\Http\Resources;

use App\Models\CartFood;
use Illuminate\Database\Eloquent\Relations\Pivot;
use Illuminate\Http\Resources\Json\JsonResource;

class CartFoodResource extends JsonResource
{
    private static $cartId;

    public static function collection($resource, $cartId = 0)
    {
        self::$cartId = $cartId;
        return parent::collection($resource); // TODO: Change the autogenerated stub
    }

    /**
     * Transform the resource into an array.
     *
     * @param \Illuminate\Http\Request $request
     * @return array|\Illuminate\Contracts\Support\Arrayable|\JsonSerializable
     */
    public function toArray($request)
    {
        return [
            "id" => $this->resource->id,
            "title" => $this->resource->title,
            "count" => CartFood::select("count")
                ->where("food_id", $this->resource->id)
                ->where("cart_id", self::$cartId)
                ->first()?->count,
            "price" => $this->resource->price,
        ];
    }
}
